services:
  db:
    build:
      context: ./backend/db
    container_name: db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    image: quizzy-backend
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mydb
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypass
      GEMINI_API_KEY: AIzaSyAUWUg9b-ZsVmTo8lmwr5VewpF28wnDEH8
      AWS_ACCESS_KEY_ID: blabla
      AWS_SECRET_ACCESS_KEY: secretdiscreet
      professor.secret.key: fiiCelMaiTare
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    image: quizzy-frontend
    container_name: frontend
    environment:
      VITE_BACKEND_URL: http://localhost:3000
    ports:
      - "36882:80"
    depends_on:
      - backend

volumes:
  pgdata:
