name: CI Tests with Docker Compose

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: docker compose up -d --build

      - name: Wait for PostgreSQL to be Ready
        run: |
          for i in {1..10}; do
            if docker exec $(docker-compose ps -q db) pg_isready -U user; then
              break
            fi
            sleep 5
          done

      - name: Wait for Spring Boot App to be Ready
        run: |
          for i in {1..10}; do
            if curl -s http://localhost:3000/actuator/health | grep '"status":"UP"'; then
              break
            fi
            sleep 5
          done

      - name: Run Integration Tests
        run: mvn verify

      - name: Shut Down Containers
        run: docker-compose down
